//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootLocker.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cityes", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Cityes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityId {
            get {
                return this.CityIdField;
            }
            set {
                if ((this.CityIdField.Equals(value) != true)) {
                    this.CityIdField = value;
                    this.RaisePropertyChanged("CityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CityName {
            get {
                return this.CityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CityNameField, value) != true)) {
                    this.CityNameField = value;
                    this.RaisePropertyChanged("CityName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FootLocker.ServiceReference1.Cityes CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UanswerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UgenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UquestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UteInumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FootLocker.ServiceReference1.Cityes City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FName {
            get {
                return this.FNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FNameField, value) != true)) {
                    this.FNameField = value;
                    this.RaisePropertyChanged("FName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LName {
            get {
                return this.LNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LNameField, value) != true)) {
                    this.LNameField = value;
                    this.RaisePropertyChanged("LName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UEmail {
            get {
                return this.UEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UEmailField, value) != true)) {
                    this.UEmailField = value;
                    this.RaisePropertyChanged("UEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPassword {
            get {
                return this.UPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UPasswordField, value) != true)) {
                    this.UPasswordField = value;
                    this.RaisePropertyChanged("UPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uanswer {
            get {
                return this.UanswerField;
            }
            set {
                if ((object.ReferenceEquals(this.UanswerField, value) != true)) {
                    this.UanswerField = value;
                    this.RaisePropertyChanged("Uanswer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubirthday {
            get {
                return this.UbirthdayField;
            }
            set {
                if ((object.ReferenceEquals(this.UbirthdayField, value) != true)) {
                    this.UbirthdayField = value;
                    this.RaisePropertyChanged("Ubirthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ugender {
            get {
                return this.UgenderField;
            }
            set {
                if ((object.ReferenceEquals(this.UgenderField, value) != true)) {
                    this.UgenderField = value;
                    this.RaisePropertyChanged("Ugender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uquestion {
            get {
                return this.UquestionField;
            }
            set {
                if ((object.ReferenceEquals(this.UquestionField, value) != true)) {
                    this.UquestionField = value;
                    this.RaisePropertyChanged("Uquestion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UteInum {
            get {
                return this.UteInumField;
            }
            set {
                if ((object.ReferenceEquals(this.UteInumField, value) != true)) {
                    this.UteInumField = value;
                    this.RaisePropertyChanged("UteInum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mailbox", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Mailbox : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MsgReadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecieverEmaillField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderFnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderLnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgBody {
            get {
                return this.MsgBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgBodyField, value) != true)) {
                    this.MsgBodyField = value;
                    this.RaisePropertyChanged("MsgBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgDate {
            get {
                return this.MsgDateField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgDateField, value) != true)) {
                    this.MsgDateField = value;
                    this.RaisePropertyChanged("MsgDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MsgRead {
            get {
                return this.MsgReadField;
            }
            set {
                if ((this.MsgReadField.Equals(value) != true)) {
                    this.MsgReadField = value;
                    this.RaisePropertyChanged("MsgRead");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MsgSubject {
            get {
                return this.MsgSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgSubjectField, value) != true)) {
                    this.MsgSubjectField = value;
                    this.RaisePropertyChanged("MsgSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecieverEmaill {
            get {
                return this.RecieverEmaillField;
            }
            set {
                if ((object.ReferenceEquals(this.RecieverEmaillField, value) != true)) {
                    this.RecieverEmaillField = value;
                    this.RaisePropertyChanged("RecieverEmaill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderEmail {
            get {
                return this.SenderEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderEmailField, value) != true)) {
                    this.SenderEmailField = value;
                    this.RaisePropertyChanged("SenderEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderFname {
            get {
                return this.SenderFnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderFnameField, value) != true)) {
                    this.SenderFnameField = value;
                    this.RaisePropertyChanged("SenderFname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderLname {
            get {
                return this.SenderLnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderLnameField, value) != true)) {
                    this.SenderLnameField = value;
                    this.RaisePropertyChanged("SenderLname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Items", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Items : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemImgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemCode {
            get {
                return this.ItemCodeField;
            }
            set {
                if ((this.ItemCodeField.Equals(value) != true)) {
                    this.ItemCodeField = value;
                    this.RaisePropertyChanged("ItemCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemImg {
            get {
                return this.ItemImgField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemImgField, value) != true)) {
                    this.ItemImgField = value;
                    this.RaisePropertyChanged("ItemImg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QntyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UemailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisaNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderDateField, value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderStatus {
            get {
                return this.OrderStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderStatusField, value) != true)) {
                    this.OrderStatusField = value;
                    this.RaisePropertyChanged("OrderStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qnty {
            get {
                return this.QntyField;
            }
            set {
                if ((this.QntyField.Equals(value) != true)) {
                    this.QntyField = value;
                    this.RaisePropertyChanged("Qnty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uemail {
            get {
                return this.UemailField;
            }
            set {
                if ((object.ReferenceEquals(this.UemailField, value) != true)) {
                    this.UemailField = value;
                    this.RaisePropertyChanged("Uemail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisaNumber {
            get {
                return this.VisaNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VisaNumberField, value) != true)) {
                    this.VisaNumberField = value;
                    this.RaisePropertyChanged("VisaNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Visa", Namespace="http://schemas.datacontract.org/2004/07/Model")]
    [System.SerializableAttribute()]
    public partial class Visa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisaTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VisanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string uEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Accountno {
            get {
                return this.AccountnoField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountnoField, value) != true)) {
                    this.AccountnoField = value;
                    this.RaisePropertyChanged("Accountno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cash {
            get {
                return this.CashField;
            }
            set {
                if ((this.CashField.Equals(value) != true)) {
                    this.CashField = value;
                    this.RaisePropertyChanged("Cash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpDate {
            get {
                return this.ExpDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpDateField, value) != true)) {
                    this.ExpDateField = value;
                    this.RaisePropertyChanged("ExpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VisaType {
            get {
                return this.VisaTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VisaTypeField, value) != true)) {
                    this.VisaTypeField = value;
                    this.RaisePropertyChanged("VisaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Visano {
            get {
                return this.VisanoField;
            }
            set {
                if ((object.ReferenceEquals(this.VisanoField, value) != true)) {
                    this.VisanoField = value;
                    this.RaisePropertyChanged("Visano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string uEmail {
            get {
                return this.uEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.uEmailField, value) != true)) {
                    this.uEmailField = value;
                    this.RaisePropertyChanged("uEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllCityes", ReplyAction="http://tempuri.org/IService1/SelectAllCityesResponse")]
        FootLocker.ServiceReference1.Cityes[] SelectAllCityes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllCityes", ReplyAction="http://tempuri.org/IService1/SelectAllCityesResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Cityes[]> SelectAllCityesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectCityByName", ReplyAction="http://tempuri.org/IService1/SelectCityByNameResponse")]
        FootLocker.ServiceReference1.Cityes SelectCityByName(string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectCityByName", ReplyAction="http://tempuri.org/IService1/SelectCityByNameResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Cityes> SelectCityByNameAsync(string cityName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectCityById", ReplyAction="http://tempuri.org/IService1/SelectCityByIdResponse")]
        FootLocker.ServiceReference1.Cityes SelectCityById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectCityById", ReplyAction="http://tempuri.org/IService1/SelectCityByIdResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Cityes> SelectCityByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderByCityName", ReplyAction="http://tempuri.org/IService1/OrderByCityNameResponse")]
        FootLocker.ServiceReference1.Cityes[] OrderByCityName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/OrderByCityName", ReplyAction="http://tempuri.org/IService1/OrderByCityNameResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Cityes[]> OrderByCityNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUserDataByEmail", ReplyAction="http://tempuri.org/IService1/DeleteUserDataByEmailResponse")]
        int DeleteUserDataByEmail(string email, string upassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteUserDataByEmail", ReplyAction="http://tempuri.org/IService1/DeleteUserDataByEmailResponse")]
        System.Threading.Tasks.Task<int> DeleteUserDataByEmailAsync(string email, string upassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select", ReplyAction="http://tempuri.org/IService1/SelectResponse")]
        FootLocker.ServiceReference1.Users[] Select();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Select", ReplyAction="http://tempuri.org/IService1/SelectResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Users[]> SelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectuserIdByEmail", ReplyAction="http://tempuri.org/IService1/SelectuserIdByEmailResponse")]
        string SelectuserIdByEmail(string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectuserIdByEmail", ReplyAction="http://tempuri.org/IService1/SelectuserIdByEmailResponse")]
        System.Threading.Tasks.Task<string> SelectuserIdByEmailAsync(string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUserByEmail", ReplyAction="http://tempuri.org/IService1/SelectUserByEmailResponse")]
        FootLocker.ServiceReference1.Users SelectUserByEmail(string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUserByEmail", ReplyAction="http://tempuri.org/IService1/SelectUserByEmailResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Users> SelectUserByEmailAsync(string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExist", ReplyAction="http://tempuri.org/IService1/CheckUserExistResponse")]
        bool CheckUserExist(string Upassword, string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExist", ReplyAction="http://tempuri.org/IService1/CheckUserExistResponse")]
        System.Threading.Tasks.Task<bool> CheckUserExistAsync(string Upassword, string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExistByEmail", ReplyAction="http://tempuri.org/IService1/CheckUserExistByEmailResponse")]
        bool CheckUserExistByEmail(string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckUserExistByEmail", ReplyAction="http://tempuri.org/IService1/CheckUserExistByEmailResponse")]
        System.Threading.Tasks.Task<bool> CheckUserExistByEmailAsync(string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetQuestion", ReplyAction="http://tempuri.org/IService1/GetQuestionResponse")]
        string GetQuestion(string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetQuestion", ReplyAction="http://tempuri.org/IService1/GetQuestionResponse")]
        System.Threading.Tasks.Task<string> GetQuestionAsync(string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PassRecovery", ReplyAction="http://tempuri.org/IService1/PassRecoveryResponse")]
        string PassRecovery(string Uemail, string PassAns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PassRecovery", ReplyAction="http://tempuri.org/IService1/PassRecoveryResponse")]
        System.Threading.Tasks.Task<string> PassRecoveryAsync(string Uemail, string PassAns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAdminExist", ReplyAction="http://tempuri.org/IService1/CheckAdminExistResponse")]
        bool CheckAdminExist(string Upassword, string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckAdminExist", ReplyAction="http://tempuri.org/IService1/CheckAdminExistResponse")]
        System.Threading.Tasks.Task<bool> CheckAdminExistAsync(string Upassword, string Uemail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        int AddUser(FootLocker.ServiceReference1.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddUser", ReplyAction="http://tempuri.org/IService1/AddUserResponse")]
        System.Threading.Tasks.Task<int> AddUserAsync(FootLocker.ServiceReference1.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserProfile", ReplyAction="http://tempuri.org/IService1/UpdateUserProfileResponse")]
        int UpdateUserProfile(FootLocker.ServiceReference1.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateUserProfile", ReplyAction="http://tempuri.org/IService1/UpdateUserProfileResponse")]
        System.Threading.Tasks.Task<int> UpdateUserProfileAsync(FootLocker.ServiceReference1.Users user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllMsg", ReplyAction="http://tempuri.org/IService1/SelectAllMsgResponse")]
        FootLocker.ServiceReference1.Mailbox[] SelectAllMsg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllMsg", ReplyAction="http://tempuri.org/IService1/SelectAllMsgResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Mailbox[]> SelectAllMsgAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectMsgByEmail", ReplyAction="http://tempuri.org/IService1/SelectMsgByEmailResponse")]
        FootLocker.ServiceReference1.Mailbox[] SelectMsgByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectMsgByEmail", ReplyAction="http://tempuri.org/IService1/SelectMsgByEmailResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Mailbox[]> SelectMsgByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ContactUs", ReplyAction="http://tempuri.org/IService1/ContactUsResponse")]
        int ContactUs(FootLocker.ServiceReference1.Mailbox m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ContactUs", ReplyAction="http://tempuri.org/IService1/ContactUsResponse")]
        System.Threading.Tasks.Task<int> ContactUsAsync(FootLocker.ServiceReference1.Mailbox m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllItems", ReplyAction="http://tempuri.org/IService1/SelectAllItemsResponse")]
        FootLocker.ServiceReference1.Items[] SelectAllItems();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllItems", ReplyAction="http://tempuri.org/IService1/SelectAllItemsResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Items[]> SelectAllItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllOrder", ReplyAction="http://tempuri.org/IService1/SelectAllOrderResponse")]
        FootLocker.ServiceReference1.Order[] SelectAllOrder(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllOrder", ReplyAction="http://tempuri.org/IService1/SelectAllOrderResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Order[]> SelectAllOrderAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUserOrder", ReplyAction="http://tempuri.org/IService1/SelectUserOrderResponse")]
        FootLocker.ServiceReference1.Order[] SelectUserOrder(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectUserOrder", ReplyAction="http://tempuri.org/IService1/SelectUserOrderResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Order[]> SelectUserOrderAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TotalOrderToPay", ReplyAction="http://tempuri.org/IService1/TotalOrderToPayResponse")]
        int TotalOrderToPay(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TotalOrderToPay", ReplyAction="http://tempuri.org/IService1/TotalOrderToPayResponse")]
        System.Threading.Tasks.Task<int> TotalOrderToPayAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        int AddOrder(FootLocker.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrder", ReplyAction="http://tempuri.org/IService1/AddOrderResponse")]
        System.Threading.Tasks.Task<int> AddOrderAsync(FootLocker.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOrder", ReplyAction="http://tempuri.org/IService1/UpdateOrderResponse")]
        int UpdateOrder(FootLocker.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateOrder", ReplyAction="http://tempuri.org/IService1/UpdateOrderResponse")]
        System.Threading.Tasks.Task<int> UpdateOrderAsync(FootLocker.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        int DeleteOrder(FootLocker.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteOrder", ReplyAction="http://tempuri.org/IService1/DeleteOrderResponse")]
        System.Threading.Tasks.Task<int> DeleteOrderAsync(FootLocker.ServiceReference1.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAccountById", ReplyAction="http://tempuri.org/IService1/SelectAccountByIdResponse")]
        FootLocker.ServiceReference1.Visa SelectAccountById(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAccountById", ReplyAction="http://tempuri.org/IService1/SelectAccountByIdResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Visa> SelectAccountByIdAsync(string uEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateVisaAccount", ReplyAction="http://tempuri.org/IService1/UpdateVisaAccountResponse")]
        int UpdateVisaAccount(double amount, FootLocker.ServiceReference1.Visa visa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateVisaAccount", ReplyAction="http://tempuri.org/IService1/UpdateVisaAccountResponse")]
        System.Threading.Tasks.Task<int> UpdateVisaAccountAsync(double amount, FootLocker.ServiceReference1.Visa visa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllAccounts", ReplyAction="http://tempuri.org/IService1/SelectAllAccountsResponse")]
        FootLocker.ServiceReference1.Visa[] SelectAllAccounts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SelectAllAccounts", ReplyAction="http://tempuri.org/IService1/SelectAllAccountsResponse")]
        System.Threading.Tasks.Task<FootLocker.ServiceReference1.Visa[]> SelectAllAccountsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FootLocker.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FootLocker.ServiceReference1.IService1>, FootLocker.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FootLocker.ServiceReference1.Cityes[] SelectAllCityes() {
            return base.Channel.SelectAllCityes();
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Cityes[]> SelectAllCityesAsync() {
            return base.Channel.SelectAllCityesAsync();
        }
        
        public FootLocker.ServiceReference1.Cityes SelectCityByName(string cityName) {
            return base.Channel.SelectCityByName(cityName);
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Cityes> SelectCityByNameAsync(string cityName) {
            return base.Channel.SelectCityByNameAsync(cityName);
        }
        
        public FootLocker.ServiceReference1.Cityes SelectCityById(int id) {
            return base.Channel.SelectCityById(id);
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Cityes> SelectCityByIdAsync(int id) {
            return base.Channel.SelectCityByIdAsync(id);
        }
        
        public FootLocker.ServiceReference1.Cityes[] OrderByCityName() {
            return base.Channel.OrderByCityName();
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Cityes[]> OrderByCityNameAsync() {
            return base.Channel.OrderByCityNameAsync();
        }
        
        public int DeleteUserDataByEmail(string email, string upassword) {
            return base.Channel.DeleteUserDataByEmail(email, upassword);
        }
        
        public System.Threading.Tasks.Task<int> DeleteUserDataByEmailAsync(string email, string upassword) {
            return base.Channel.DeleteUserDataByEmailAsync(email, upassword);
        }
        
        public FootLocker.ServiceReference1.Users[] Select() {
            return base.Channel.Select();
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Users[]> SelectAsync() {
            return base.Channel.SelectAsync();
        }
        
        public string SelectuserIdByEmail(string Uemail) {
            return base.Channel.SelectuserIdByEmail(Uemail);
        }
        
        public System.Threading.Tasks.Task<string> SelectuserIdByEmailAsync(string Uemail) {
            return base.Channel.SelectuserIdByEmailAsync(Uemail);
        }
        
        public FootLocker.ServiceReference1.Users SelectUserByEmail(string Uemail) {
            return base.Channel.SelectUserByEmail(Uemail);
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Users> SelectUserByEmailAsync(string Uemail) {
            return base.Channel.SelectUserByEmailAsync(Uemail);
        }
        
        public bool CheckUserExist(string Upassword, string Uemail) {
            return base.Channel.CheckUserExist(Upassword, Uemail);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserExistAsync(string Upassword, string Uemail) {
            return base.Channel.CheckUserExistAsync(Upassword, Uemail);
        }
        
        public bool CheckUserExistByEmail(string Uemail) {
            return base.Channel.CheckUserExistByEmail(Uemail);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserExistByEmailAsync(string Uemail) {
            return base.Channel.CheckUserExistByEmailAsync(Uemail);
        }
        
        public string GetQuestion(string Uemail) {
            return base.Channel.GetQuestion(Uemail);
        }
        
        public System.Threading.Tasks.Task<string> GetQuestionAsync(string Uemail) {
            return base.Channel.GetQuestionAsync(Uemail);
        }
        
        public string PassRecovery(string Uemail, string PassAns) {
            return base.Channel.PassRecovery(Uemail, PassAns);
        }
        
        public System.Threading.Tasks.Task<string> PassRecoveryAsync(string Uemail, string PassAns) {
            return base.Channel.PassRecoveryAsync(Uemail, PassAns);
        }
        
        public bool CheckAdminExist(string Upassword, string Uemail) {
            return base.Channel.CheckAdminExist(Upassword, Uemail);
        }
        
        public System.Threading.Tasks.Task<bool> CheckAdminExistAsync(string Upassword, string Uemail) {
            return base.Channel.CheckAdminExistAsync(Upassword, Uemail);
        }
        
        public int AddUser(FootLocker.ServiceReference1.Users user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<int> AddUserAsync(FootLocker.ServiceReference1.Users user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public int UpdateUserProfile(FootLocker.ServiceReference1.Users user) {
            return base.Channel.UpdateUserProfile(user);
        }
        
        public System.Threading.Tasks.Task<int> UpdateUserProfileAsync(FootLocker.ServiceReference1.Users user) {
            return base.Channel.UpdateUserProfileAsync(user);
        }
        
        public FootLocker.ServiceReference1.Mailbox[] SelectAllMsg() {
            return base.Channel.SelectAllMsg();
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Mailbox[]> SelectAllMsgAsync() {
            return base.Channel.SelectAllMsgAsync();
        }
        
        public FootLocker.ServiceReference1.Mailbox[] SelectMsgByEmail(string email) {
            return base.Channel.SelectMsgByEmail(email);
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Mailbox[]> SelectMsgByEmailAsync(string email) {
            return base.Channel.SelectMsgByEmailAsync(email);
        }
        
        public int ContactUs(FootLocker.ServiceReference1.Mailbox m) {
            return base.Channel.ContactUs(m);
        }
        
        public System.Threading.Tasks.Task<int> ContactUsAsync(FootLocker.ServiceReference1.Mailbox m) {
            return base.Channel.ContactUsAsync(m);
        }
        
        public FootLocker.ServiceReference1.Items[] SelectAllItems() {
            return base.Channel.SelectAllItems();
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Items[]> SelectAllItemsAsync() {
            return base.Channel.SelectAllItemsAsync();
        }
        
        public FootLocker.ServiceReference1.Order[] SelectAllOrder(string uEmail) {
            return base.Channel.SelectAllOrder(uEmail);
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Order[]> SelectAllOrderAsync(string uEmail) {
            return base.Channel.SelectAllOrderAsync(uEmail);
        }
        
        public FootLocker.ServiceReference1.Order[] SelectUserOrder(string uEmail) {
            return base.Channel.SelectUserOrder(uEmail);
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Order[]> SelectUserOrderAsync(string uEmail) {
            return base.Channel.SelectUserOrderAsync(uEmail);
        }
        
        public int TotalOrderToPay(string uEmail) {
            return base.Channel.TotalOrderToPay(uEmail);
        }
        
        public System.Threading.Tasks.Task<int> TotalOrderToPayAsync(string uEmail) {
            return base.Channel.TotalOrderToPayAsync(uEmail);
        }
        
        public int AddOrder(FootLocker.ServiceReference1.Order order) {
            return base.Channel.AddOrder(order);
        }
        
        public System.Threading.Tasks.Task<int> AddOrderAsync(FootLocker.ServiceReference1.Order order) {
            return base.Channel.AddOrderAsync(order);
        }
        
        public int UpdateOrder(FootLocker.ServiceReference1.Order order) {
            return base.Channel.UpdateOrder(order);
        }
        
        public System.Threading.Tasks.Task<int> UpdateOrderAsync(FootLocker.ServiceReference1.Order order) {
            return base.Channel.UpdateOrderAsync(order);
        }
        
        public int DeleteOrder(FootLocker.ServiceReference1.Order order) {
            return base.Channel.DeleteOrder(order);
        }
        
        public System.Threading.Tasks.Task<int> DeleteOrderAsync(FootLocker.ServiceReference1.Order order) {
            return base.Channel.DeleteOrderAsync(order);
        }
        
        public FootLocker.ServiceReference1.Visa SelectAccountById(string uEmail) {
            return base.Channel.SelectAccountById(uEmail);
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Visa> SelectAccountByIdAsync(string uEmail) {
            return base.Channel.SelectAccountByIdAsync(uEmail);
        }
        
        public int UpdateVisaAccount(double amount, FootLocker.ServiceReference1.Visa visa) {
            return base.Channel.UpdateVisaAccount(amount, visa);
        }
        
        public System.Threading.Tasks.Task<int> UpdateVisaAccountAsync(double amount, FootLocker.ServiceReference1.Visa visa) {
            return base.Channel.UpdateVisaAccountAsync(amount, visa);
        }
        
        public FootLocker.ServiceReference1.Visa[] SelectAllAccounts() {
            return base.Channel.SelectAllAccounts();
        }
        
        public System.Threading.Tasks.Task<FootLocker.ServiceReference1.Visa[]> SelectAllAccountsAsync() {
            return base.Channel.SelectAllAccountsAsync();
        }
    }
}
